### ISSUE TITLE
Scaffold fails where tables contain non-English characters.

### ISSUE THREAD

**Issue by yabbas** [frenesim/schema_to_scaffold#17]
I have a table whose headers are in the Arabic language - Scaffold fails with the following:
C:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/schema_to_scaffold-0.5.4/lib/schema_to_scaffold/table.rb:15:in `map': undefined method`to_script' for nil:
NilClass (NoMethodError)
        from C:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/schema_to_scaffold-0.5.4/lib/schema_to_scaffold/table.rb:15:in `to_script'
        from C:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/schema_to_scaffold-0.5.4/lib/schema_to_scaffold.rb:84:in`generate_script'
        from C:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/schema_to_scaffold-0.5.4/bin/scaffold:57:in `block in <top (required)>'
        from C:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/schema_to_scaffold-0.5.4/bin/scaffold:57:in`each'
        from C:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/schema_to_scaffold-0.5.4/bin/scaffold:57:in `<top (required)>'
        from C:/RailsInstaller/Ruby2.0.0/bin/scaffold:23:in`load'
        from C:/RailsInstaller/Ruby2.0.0/bin/scaffold:23:in `<main>'

Is there an easy fix?

**Comment by frenesim** [comment]
true. it's not rails convention
