### ISSUE TITLE
Multiple Tables won't -c correctly in Windows

### ISSUE THREAD

**Issue by ttilberg** [frenesim/schema_to_scaffold#21]
Hello,

I've recently started developing with Ruby in several environments, one of which is Windows.

I've found a bug (or at least something that might need better documentation) where when trying to scaffold multiple tables with the -c clipboard argument, only the first line of `output` is processed in:

``` ruby
   when /mingw/i  then exec("echo '#{output}' | clip")
```

Only the first line of `output` ends up in the exec

Sample Output:

```
Select a table: *

Script for scaffold:

rails generate scaffold Client name:string website:string contact_name:string notes:string contact_email:string contact_phone:string --no-migration

rails generate scaffold TargetLocation name:string address:string city:string state:string zip:string cbsa_code:string cbsa_name:string latitude:decimal longitude:decimal target:references --no-migration

rails generate scaffold Target name:string website_url:string multi_location:boolean input_notes:string --no-migration


(copied to your clipboard)
'rails generate scaffold Client name:string website:string contact_name:string notes:string contact_email:string contact_phone:string --no-migration
```

And it just ends there. Nothing gets sent to | clip. Thankfully, because of the `'` encapsulation, that single generate statement doesn't actually exec(), even though it never made it to | clip. 

Obviously at hand, is how inversatile Windows CMD is, and what to do with the newline characters. I assume if I were running CYGWIN or something, it might have been handled better. Perhaps a better default behaviour for Windows multiline output is to return a format separated by some other string token that can be manually replaced later.

If I am able to come up with a solution, I'll submit the code. 

Of note, from within the RubyMine terminal emulator (in Windows) I executed `ruby scaffold -c -p /path/to/db` and it worked as expected. So, again, I think this is due to the inversatility of cmd.exe. Perhaps this should just be in the documentation, similar to the dependency for xclip.

Windows 7 x64
Ruby 2.2.0
x64-mingw32

**Comment by ttilberg** [comment]
I wonder if a workaround is to have an option to generate a .rb file that can act as a script? Since obviously all users would have Ruby installed, that would normalize the environment. You could have an option to output 'schema_to_scaffold.rb' in the root of a project directory or something, and maybe it looks like:

```
exec 'rails generate scaffold Client name:string website:string contact_name:string notes:string contact_email:string contact_phone:string --no-migration'
exec 'rails generate scaffold TargetLocation name:string address:string city:string state:string zip:string cbsa_code:string cbsa_name:string latitude:decimal longitude:decimal target_id:integer --no-migration'
exec 'rails generate scaffold TargetProxy target_id:integer proxy_id:integer --no-migration'
```

Then the user could easily execute the script with `ruby schema_to_scaffold.rb` regardless of OS environment. I'm really new to a lot of this, so maybe this won't actually work, but it's what I ended up doing to get my scripts to generate for my current project.

**Comment by ttilberg** [comment]
Sorry for the spam. I'm not good with GitHub yet, and accidentally clicked the close button when trying to comment.

I was just going to suggest, perhaps an argument to write the scripts to a file would be helpful for chumps stuck on Windows. I originally thought "Maybe generate a .rb script that exec() or system()'s the commands, but even that has problems on basic Windows without CYGWIN installed ( exec() and system() use Kernel.fork() but

`(eval):7:in `fork': fork() function is unimplemented on this machine (NotImplementedError)`

Anyway, maybe a text file generation option would be helpful in addition to the -c |clip option.

**Comment by dankohn** [comment]
I'm not surprised that the Windows clipboard support doesn't work, since we
don't have a Windows machine to test it on. The OS X support didn't work
until I fixed it.

Humberto has been very open to accepting patches, so I encourage you to
write one for Windows that addresses your needs.

--
Dan Kohn <mailto:dan@dankohn.com>
tel:+1-415-233-1000

**Comment by ttilberg** [comment]
I took a few stabs at it, but kept hitting roadblocks. I'm a very new programmer, so there's probably something I am overlooking that can be done. If I do come up with something, I'll be sure to share it! I do appreciate that this tool exists -- even if it's hard to use on my Windows machine, it's great on my osx and linux!

**Comment by frenesim** [comment]
Hi ttilberg. Thanks for your interest in this tool. Almost 2 years later... The option -c doesn't work in windows.
