### ISSUE TITLE
unexpected token `<'`

### ISSUE THREAD

**Issue by noahfin** [frenesim/schema_to_scaffold#26]
This gem seems like A good idea to help people like me learn how to make forms and controllers for joined tables, but it's not working 
`$   rails generate scaffold <todo> <title[:string]>
-bash: syntax error near unexpected token `<'`

Is this project forgotten about or did I miss an install script?

**Comment by noahfin** [comment]
Sorry I found this. I would suggest adding this script to the readme. I think it will make much easy for others to use this gem.
`scaffold -c -p ~/path_to_rails_app/db/schema.rb`

**Comment by dankohn** [comment]
Pull requests to improve documentation are welcome.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by matt17r** [comment]
> I would suggest adding this script to the readme...
> `scaffold -c -p ~/path_to_rails_app/db/schema.rb`

The usage instructions already include `scaffold -c -p ~/work/rails/my_app/db/schema.rb`.

I think this issue can be closed.
